# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Eat Good Food Group
email: webmaster@eatgoodfoodgroup.com
description: > # this means to ignore newlines until "baseurl:"
  The home of Eat Good Food Group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eatgoodfoodgroup.com" # the base hostname & protocol for your site
twitter_username_eamonns: eamonnschipper
twitter_username_eve: restaurant_eve
twitter_username_sf: societyfair
twitter_username_px: BarPX
facebook_username_eamonns: EamonnsADublinChipper
facebook_username_eve: restauranteve
facebook_username_sf: societyfair
facebook_username_px: BarPX
instagram_username_eamonns: EamonnsADublinChipper
instagram_username_eve: restaurant_eve
instagram_username_sf: societyfair
instagram_username_px: barpx

# Build settings
markdown: kramdown

gems: [jekyll-twitter-plugin]
# This will require each of these gems automatically.

twitter:
  consumer_key: u4bNr3wscNWmLMoNBGB3DDr0E
  consumer_secret: J3xMMADHpWU9Gm3yRbT0idIC9W35NSnv6ZScuczpRaZOIym7I2
  access_token: 108386929-FdbK082StLm4Gr2IintLbBVZTajYCUQZMfgjVlV6
  access_token_secret: DnHMw9eGgjB5LoIeXSBPFSO4DU5O4vUw2oLC2MSXkpidF

# Configure prose.io.
prose:
  rooturl: '_posts'
  siteurl: 'http://eatgoodfood.github.io'
  relativeLinks: 'http://eatgoodfood.github.io/links.jsonp'
  media: 'media'
  ignore:
    - index.html
    - _config.yml
    - CNAME
    - /_layouts
    - /_includes
    - /_plugins
    - /_sass
  siteurl: "http://eatgoodfoodgroup.com"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Choose Tags"
          options:
            - name: "Update"
              value: "update"